Pandas Workshop:

Hands-on workshop to solve problems based on real-time projects.

Note:
1. This is NOT A TEST, please feel free to google stuff, refer documentations, stackoverflow, etc.
2. Please do not use any form of GenAI.


Topics covered:

1. File handling
2. Filter
3. Groupby and Aggregate
4. Sort
5. Joins

Tip: 

Understand the data first before proceeding.

Focus on how you solve the problem with pen and paper first, imagine it, then implement it in code.

Solve the problems first and implement it later

Use the .csv files:

1. customers_5000.csv
2. transactions_5000.csv

1 - Total spend per customer

Find total amount spent by each customer (only those who have transactions). 
Return the top 10 customers by total spend.

In [4]:
import pandas as pd

customer = pd.read_csv(r"D:\Machine Learning\Workshop - 1\sources\customers_5000.csv")
transaction = pd.read_csv(r"D:\Machine Learning\Workshop - 1\sources\transactions_5000.csv")

transaction['transaction_date'] = pd.to_datetime(transaction['transaction_date'])
customer['signup_date'] = pd.to_datetime(customer['signup_date'])

In [5]:
customer.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27

In [14]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23
3,500003,101299,Clothing,178.91,2,Card,2021-03-08
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18

In [16]:
info = transaction.groupby(['customer_id']).agg(
    total_revenue = ('amount','sum')
).reset_index()
info

      customer_id  total_revenue
0          100001        3066.17
1          100002        3822.43
2          100004        5002.57
3          100005        1402.59
4          100006        2062.09
...           ...            ...
2529       200007         382.76
2530       200011        2163.66
2531       200015         697.56
2532       200017        3853.99
2533       200019        1774.92

[2534 rows x 2 columns]

In [11]:
info['rank'] = info['total_revenue'].rank(method = 'dense',ascending = False)

In [12]:
info[info['rank'] <=10].sort_values('rank')

      customer_id  total_revenue  rank
1586       103080       19897.33   1.0
681        101304       16236.50   2.0
917        101747       15876.53   3.0
113        100207       15302.52   4.0
324        100619       14944.99   5.0
2144       104256       14480.42   6.0
819        101543       14134.31   7.0
2041       104026       14124.59   8.0
905        101723       13992.94   9.0
1638       103179       12944.99  10.0

2 - Customers with no transactions

List customers from cust who do not appear in the txn table (i.e., zero transactions).

In [3]:
non_tran = pd.merge(customer, transaction, left_on = 'customer_id', right_on = 'customer_id', how = "left")

In [4]:
non_tran.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date,transaction_id,product_category,amount,quantity,payment_method,transaction_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,NaN,NaN,NaN,NaN,NaN,NaN
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18,501924.0,Home,3066.17,4.0,Card,2024-05-17
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04,502592.0,Sports,3514.58,2.0,Netbanking,2022-05-01
3,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04,503258.0,Groceries,307.85,1.0,UPI,2024-01-10
4,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
non_tran = non_tran[non_tran['transaction_id'].isnull()]

In [28]:
non_tran.head(10)

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date,transaction_id,product_category,amount,quantity,payment_method,transaction_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,NaN,NaN,NaN,NaN,NaN,NaN
4,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN
13,100007,Morgan,Malhotra,Lucknow,F,19,18-25,2021-05-23,NaN,NaN,NaN,NaN,NaN,NaN
16,100009,Taylor,Bhat,Ahmedabad,F,27,26-35,2022-01-22,NaN,NaN,NaN,NaN,NaN,NaN
19,100012,Rowan,Chopra,Hyderabad,F,41,36-50,2022-08-13,NaN,NaN,NaN,NaN,NaN,NaN
42,100023,Drew,Chopra,Mumbai,F,28,26-35,2024-04-19,NaN,NaN,NaN,NaN,NaN,NaN
44,100025,Alex,Joshi,Hyderabad,M,21,18-25,2019-04-20,NaN,NaN,NaN,NaN,NaN,NaN
51,100027,Peyton,Rao,Delhi,M,43,36-50,2023-08-10,NaN,NaN,NaN,NaN,NaN,NaN
53,100029,Cameron,Chatterjee,Bengaluru,M,67,51-70,2022-12-12,NaN,NaN,NaN,NaN,NaN,NaN
57,100031,Morgan,Iyer,Hyderabad,M,48,36-50,2019-07-17,NaN,NaN,NaN,NaN,NaN,NaN

3 - Monthly revenue by product category

Compute monthly revenue (sum of amount) per product_category. Return results sorted by month then revenue descending.

In [30]:
transaction['product_category'].unique()

array(['Toys', 'Clothing', 'Electronics', 'Beauty', 'Sports', 'Groceries',
       'Home', 'Books'], dtype=object)

In [31]:
transaction['transaction_date'] = pd.to_datetime(transaction['transaction_date'])

In [17]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    5000 non-null   int64
 1   customer_id       5000 non-null   int64
 2   product_category  5000 non-null   object
 3   amount            5000 non-null   float64
 4   quantity          5000 non-null   int64
 5   payment_method    5000 non-null   object
 6   transaction_date  5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 273.6+ KB

In [19]:
transaction['month'] = pd.to_datetime(transaction['transaction_date']).dt.month
transaction['year'] = pd.to_datetime(transaction['transaction_date']).dt.year

In [20]:
transaction

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date,month,year
0,500000,100897,Toys,670.85,1,UPI,2024-12-22,12,2024
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31,5,2024
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23,1,2021
3,500003,101299,Clothing,178.91,2,Card,2021-03-08,3,2021
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18,9,2022
...,...,...,...,...,...,...,...,...,...
4995,504995,101819,Clothing,313.27,3,Netbanking,2024-06-12,6,2024
4996,504996,200006,Groceries,584.47,1,Card,2022-12-15,12,2022
4997,504997,103642,Toys,1049.75,3,UPI,2022-07-06,7,2022
4998,504998,103508,Sports,463.81,2,Card,2022-12-12,12,2022
4999,504999,101381,Beauty,7346.35,1,Card,2023-08-19,8,2023

In [28]:
mon_sep = transaction.groupby(['year','month','product_category']).agg(
    monthly_revenue = ('amount','sum')
).reset_index()

In [29]:
mon_sep

     year  month product_category  monthly_revenue
0    2021      1           Beauty          9615.45
1    2021      1            Books          4578.77
2    2021      1         Clothing         22907.79
3    2021      1      Electronics         27968.26
4    2021      1        Groceries         35574.53
..    ...    ...              ...              ...
378  2024     12      Electronics         29858.08
379  2024     12        Groceries         48235.72
380  2024     12             Home          2677.92
381  2024     12           Sports         10726.79
382  2024     12             Toys         16166.41

[383 rows x 4 columns]

In [46]:
mon_sep.sort_values(by=['year','month','monthly_revenue'], ascending =[True,True,False]).head(10)

    year  month product_category  monthly_revenue
4   2021      1        Groceries         35574.53
3   2021      1      Electronics         27968.26
2   2021      1         Clothing         22907.79
6   2021      1           Sports         12968.09
0   2021      1           Beauty          9615.45
5   2021      1             Home          9067.95
7   2021      1             Toys          5886.19
1   2021      1            Books          4578.77
12  2021      2        Groceries         48139.22
13  2021      2             Home         18168.36

4 - Top 3 product categories per customer by spend

For each customer, list their top 3 product categories by total spend (amount) and the rank (1 = highest).

In [2]:
customer.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27

In [3]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23
3,500003,101299,Clothing,178.91,2,Card,2021-03-08
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18

In [92]:
top = pd.merge(transaction,customer, left_on = 'customer_id', right_on = 'customer_id', how = 'left')
top

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date,first_name,last_name,city,gender,age,age_group,signup_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22,Rowan,Bhat,Jaipur,F,67.0,51-70,2021-08-07
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31,Alex,Verma,Lucknow,F,39.0,36-50,2024-11-09
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23,Sam,Chatterjee,Hyderabad,M,59.0,51-70,2022-03-05
3,500003,101299,Clothing,178.91,2,Card,2021-03-08,Peyton,Kohli,Jaipur,F,24.0,18-25,2023-06-05
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18,Jordan,Kumar,Pune,F,24.0,18-25,2018-04-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,504995,101819,Clothing,313.27,3,Netbanking,2024-06-12,Taylor,Bose,Pune,M,40.0,36-50,2021-09-29
4996,504996,200006,Groceries,584.47,1,Card,2022-12-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,504997,103642,Toys,1049.75,3,UPI,2022-07-06,Jordan,Iyer,Lucknow,M,19.0,18-25,2021-01-16
4998,504998,103508,Sports,463.81,2,Card,2022-12-12,Harper,Kohli,Chennai,F,32.0,26-35,2022-01-01
4999,504999,101381,Beauty,7346.35,1,Card,2023-08-19,Peyton,Sharma,Lucknow,F,54.0,51-70,2019-08-16

In [93]:
top = top.groupby(['customer_id','product_category']).agg(
    total_spend = ('amount','sum')
).reset_index()
top

      customer_id product_category  total_spend
0          100001             Home      3066.17
1          100002        Groceries       307.85
2          100002           Sports      3514.58
3          100004         Clothing       801.62
4          100004      Electronics      2654.79
...           ...              ...          ...
4378       200011        Groceries      2163.66
4379       200015         Clothing       697.56
4380       200017        Groceries      2001.34
4381       200017             Home      1852.65
4382       200019           Beauty      1774.92

[4383 rows x 3 columns]

In [94]:
top['rank'] =(
    top.groupby('customer_id')['total_spend']
       .rank(method = 'dense', ascending = False)
)

In [95]:
top.head(10)

   customer_id product_category  total_spend  rank
0       100001             Home      3066.17   1.0
1       100002        Groceries       307.85   2.0
2       100002           Sports      3514.58   1.0
3       100004         Clothing       801.62   3.0
4       100004      Electronics      2654.79   1.0
5       100004           Sports      1546.16   2.0
6       100005         Clothing      1402.59   1.0
7       100006           Beauty      1784.41   1.0
8       100006         Clothing       277.68   2.0
9       100008        Groceries      1602.26   1.0

5 - Average basket size and high-value customers

Compute for each customer:
	•	avg_basket_value = sum(amount)/count(transactions)
    
Then list customers with avg_basket_value > 2000 and at least 5 transactions, sorted by avg_basket_value desc.

In [2]:
customer.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27

In [3]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23
3,500003,101299,Clothing,178.91,2,Card,2021-03-08
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18

In [4]:
# avg_basket_value = sum(amount) /  count(transactions)
# avg_basket_value > 2000 and at least 5 transactions, sorted by avg_basket_value desc.

transaction['avg_basket_value'] = (
    transaction.groupby(['customer_id'])['amount'].transform('sum') 
    / transaction.groupby(['customer_id'])['transaction_id'].transform('nunique')
)

In [5]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date,avg_basket_value
0,500000,100897,Toys,670.85,1,UPI,2024-12-22,499.305
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31,654.910
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23,866.595
3,500003,101299,Clothing,178.91,2,Card,2021-03-08,178.910
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18,467.835

In [13]:
transaction['tnx_count'] = transaction.groupby(['customer_id'])['transaction_id'].transform('count')
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date,avg_basket_value,tnx_count
0,500000,100897,Toys,670.85,1,UPI,2024-12-22,499.305,2
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31,654.910,3
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23,866.595,2
3,500003,101299,Clothing,178.91,2,Card,2021-03-08,178.910,1
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18,467.835,4

In [28]:
sol = transaction.groupby(['customer_id','tnx_count','avg_basket_value']).agg(
    total_amount = ('amount' , 'sum')
).reset_index()

sol

      customer_id  tnx_count  avg_basket_value  total_amount
0          100001          1          3066.170       3066.17
1          100002          2          1911.215       3822.43
2          100004          5          1000.514       5002.57
3          100005          1          1402.590       1402.59
4          100006          2          1031.045       2062.09
...           ...        ...               ...           ...
2529       200007          1           382.760        382.76
2530       200011          1          2163.660       2163.66
2531       200015          1           697.560        697.56
2532       200017          2          1926.995       3853.99
2533       200019          1          1774.920       1774.92

[2534 rows x 4 columns]

In [29]:
sol[ (sol['avg_basket_value'] > 2000) & (sol['tnx_count'] >= 5)].sort_values('avg_basket_value', ascending = False)

      customer_id  tnx_count  avg_basket_value  total_amount
324        100619          5       2988.998000      14944.99
2041       104026          5       2824.918000      14124.59
2144       104256          6       2413.403333      14480.42
819        101543          6       2355.718333      14134.31
681        101304          7       2319.500000      16236.50
1675       103271          5       2205.466000      11027.33
1638       103179          6       2157.498333      12944.99
1761       103442          5       2134.426000      10672.13
356        100684          5       2084.706000      10423.53
2240       104445          5       2053.950000      10269.75
936        101786          5       2001.248000      10006.24

6 - Join + city-level metrics

Join cust and txn (only matching customers) to compute per-city:

	•	total customers (distinct),

	•	total transactions,

	•	total revenue,

	•	average revenue per customer.


Return cities sorted by total revenue descending.

In [11]:
customer.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27

In [12]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23
3,500003,101299,Clothing,178.91,2,Card,2021-03-08
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18

In [16]:
# pd.merge(transaction, customer, left_on = 'customer_id', right_on = 'customer_id', how = 'inner')

In [20]:
trans_data = transaction.groupby(['customer_id','transaction_id']).agg(
    {'amount' : 'sum'}
).reset_index()

trans_data

      customer_id  transaction_id   amount
0          100001          501924  3066.17
1          100002          502592  3514.58
2          100002          503258   307.85
3          100004          500356   801.62
4          100004          500903   863.09
...           ...             ...      ...
4995       200011          500099  2163.66
4996       200015          500179   697.56
4997       200017          501344  2001.34
4998       200017          504329  1852.65
4999       200019          500634  1774.92

[5000 rows x 3 columns]

In [25]:
data = pd.merge(trans_data,customer, left_on = 'customer_id',right_on = 'customer_id', how = 'left')
data

,customer_id,transaction_id,amount,first_name,last_name,city,gender,age,age_group,signup_date
0,100001,501924,3066.17,Rowan,Saxena,Delhi,M,52.0,51-70,2021-07-18
1,100002,502592,3514.58,Morgan,Verma,Ahmedabad,M,38.0,36-50,2021-02-04
2,100002,503258,307.85,Morgan,Verma,Ahmedabad,M,38.0,36-50,2021-02-04
3,100004,500356,801.62,Avery,Saxena,Bengaluru,F,36.0,36-50,2022-06-27
4,100004,500903,863.09,Avery,Saxena,Bengaluru,F,36.0,36-50,2022-06-27
...,...,...,...,...,...,...,...,...,...,...
4995,200011,500099,2163.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,200015,500179,697.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,200017,501344,2001.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,200017,504329,1852.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,200019,500634,1774.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
data = data.dropna()

In [32]:
data

,customer_id,transaction_id,amount,first_name,last_name,city,gender,age,age_group,signup_date
0,100001,501924,3066.17,Rowan,Saxena,Delhi,M,52.0,51-70,2021-07-18
1,100002,502592,3514.58,Morgan,Verma,Ahmedabad,M,38.0,36-50,2021-02-04
2,100002,503258,307.85,Morgan,Verma,Ahmedabad,M,38.0,36-50,2021-02-04
3,100004,500356,801.62,Avery,Saxena,Bengaluru,F,36.0,36-50,2022-06-27
4,100004,500903,863.09,Avery,Saxena,Bengaluru,F,36.0,36-50,2022-06-27
...,...,...,...,...,...,...,...,...,...,...
4980,104991,503703,297.39,Alex,Bose,Kolkata,M,55.0,51-70,2022-12-31
4981,104992,500389,680.46,Skyler,Joshi,Bengaluru,F,56.0,51-70,2023-01-08
4982,104992,500536,386.75,Skyler,Joshi,Bengaluru,F,56.0,51-70,2023-01-08
4983,104993,500519,418.97,Skyler,Ahuja,Pune,F,66.0,51-70,2019-09-10
4984,104998,504860,1714.32,Casey,Kumar,Lucknow,F,61.0,51-70,2019-05-05

In [ ]:
Join cust and txn (only matching customers) to compute per-city:

	•	total customers (distinct),

	•	total transactions,

	•	total revenue,

	•	average revenue per customer.


Return cities sorted by total revenue descending.

In [83]:
a = data.groupby(['city']).agg(
    total_customers = ('customer_id','nunique'),
    total_transactions =('transaction_id' , 'count'),
    total_revenue = ('amount', 'sum'),
).reset_index()
a

        city  total_customers  total_transactions  total_revenue
0  Ahmedabad              237                 443      511990.85
1  Bengaluru              251                 511      636106.82
2    Chennai              249                 497      607912.35
3      Delhi              245                 483      589264.98
4  Hyderabad              265                 501      637652.44
5     Jaipur              258                 496      625597.35
6    Kolkata              260                 521      644860.81
7    Lucknow              258                 521      625934.48
8     Mumbai              253                 516      639247.91
9       Pune              245                 486      588478.40

In [84]:
a['avg_rev_per_customer'] = a['total_revenue'] / a['total_customers']

In [87]:
a.sort_values('total_revenue',ascending = False)

,city,total_customers,total_transactions,total_revenue,avg_rev_per_customer
6,Kolkata,260,521,644860.81,2480.233885
8,Mumbai,253,516,639247.91,2526.671581
4,Hyderabad,265,501,637652.44,2406.235623
1,Bengaluru,251,511,636106.82,2534.290120
7,Lucknow,258,521,625934.48,2426.102636
5,Jaipur,258,496,625597.35,2424.795930
2,Chennai,249,497,607912.35,2441.415060
3,Delhi,245,483,589264.98,2405.163184
9,Pune,245,486,588478.40,2401.952653
0,Ahmedabad,237,443,511990.85,2160.298945

7 - Most recent transaction and recency rank per customer

For every customer in cust (including those with no transactions), find:

	•	their most recent transaction date (NaT if none)

	•	a recency_rank that ranks customers by recency (1 = most recent). Customers with no transactions should get rank as NaN (or placed at end).

In [88]:
customer.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27

In [89]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23
3,500003,101299,Clothing,178.91,2,Card,2021-03-08
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18

In [97]:
df1 = pd.merge(customer, transaction, left_on = 'customer_id', right_on = 'customer_id', how = 'left')
df1

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date,transaction_id,product_category,amount,quantity,payment_method,transaction_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,NaN,NaN,NaN,NaN,NaN,NaT
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18,501924.0,Home,3066.17,4.0,Card,2024-05-17
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04,502592.0,Sports,3514.58,2.0,Netbanking,2022-05-01
3,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04,503258.0,Groceries,307.85,1.0,UPI,2024-01-10
4,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7455,104995,Alex,Bose,Delhi,M,57,51-70,2023-12-23,NaN,NaN,NaN,NaN,NaN,NaT
7456,104996,Jordan,Sharma,Ahmedabad,M,29,26-35,2019-08-03,NaN,NaN,NaN,NaN,NaN,NaT
7457,104997,Taylor,Chopra,Mumbai,M,31,26-35,2021-03-16,NaN,NaN,NaN,NaN,NaN,NaT
7458,104998,Casey,Kumar,Lucknow,F,61,51-70,2019-05-05,504860.0,Sports,1714.32,2.0,UPI,2022-02-22
7459,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,NaN,NaN,NaN,NaN,NaN,NaT

In [102]:
df1['transaction_date'].max()

Timestamp('2024-12-30 00:00:00')

In [103]:
df1['transaction_date'].min()

Timestamp('2021-01-01 00:00:00')

In [156]:
df2 = df1.groupby(['customer_id','first_name','last_name','city','gender','age','signup_date']).agg(
     last_transaction_date = ('transaction_date' , 'max'),
     
     #recency_ranking = ('transaction_date', 'rank')
).reset_index()
df2 = df2.dropna()
df2

,customer_id,first_name,last_name,city,gender,age,signup_date,last_transaction_date
1,100001,Rowan,Saxena,Delhi,M,52,2021-07-18,2024-05-17
2,100002,Morgan,Verma,Ahmedabad,M,38,2021-02-04,2024-01-10
4,100004,Avery,Saxena,Bengaluru,F,36,2022-06-27,2024-12-05
5,100005,Avery,Iyer,Hyderabad,F,48,2023-12-10,2022-10-21
6,100006,Skyler,Sharma,Hyderabad,M,49,2019-04-12,2022-09-18
...,...,...,...,...,...,...,...,...
4979,104989,Avery,Gupta,Delhi,F,35,2023-06-01,2024-11-27
4981,104991,Alex,Bose,Kolkata,M,55,2022-12-31,2023-01-02
4982,104992,Skyler,Joshi,Bengaluru,F,56,2023-01-08,2023-02-13
4983,104993,Skyler,Ahuja,Pune,F,66,2019-09-10,2023-08-12
4988,104998,Casey,Kumar,Lucknow,F,61,2019-05-05,2022-02-22

In [157]:
df2['recency_rank'] = df2['last_transaction_date'].rank(method = 'dense', ascending = False)

In [158]:
df2.sort_values('recency_rank', ascending = True).head(10)

,customer_id,first_name,last_name,city,gender,age,signup_date,last_transaction_date,recency_rank
2927,102935,Riley,Sharma,Jaipur,F,57,2024-04-24,2024-12-30,1.0
3672,103681,Morgan,Gupta,Jaipur,O,41,2022-12-30,2024-12-30,1.0
4168,104178,Reese,Iyer,Kolkata,M,27,2018-04-14,2024-12-30,1.0
437,100437,Drew,Das,Ahmedabad,F,63,2024-08-24,2024-12-29,2.0
1771,101772,Drew,Rao,Lucknow,F,45,2020-06-10,2024-12-29,2.0
2001,102002,Harper,Kohli,Delhi,M,36,2022-03-21,2024-12-29,2.0
4640,104650,Morgan,Bhat,Ahmedabad,M,52,2019-06-14,2024-12-28,3.0
3494,103502,Rowan,Rao,Bengaluru,M,54,2020-08-01,2024-12-28,3.0
1577,101578,Riley,Mehta,Bengaluru,F,54,2022-11-04,2024-12-28,3.0
1423,101424,Skyler,Ahuja,Chennai,M,66,2022-03-29,2024-12-28,3.0

8 - Top N customers per city by lifetime spend 

For each city, find top 2 customers by lifetime spend (sum of amount). Return a dataframe with city, customer_id, total_spend, and rank_within_city.

In [159]:
customer.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27

In [160]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23
3,500003,101299,Clothing,178.91,2,Card,2021-03-08
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18

In [166]:
s1 = pd.merge(transaction, customer, left_on = 'customer_id', right_on = 'customer_id', how = 'left')
s1.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date,first_name,last_name,city,gender,age,age_group,signup_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22,Rowan,Bhat,Jaipur,F,67.0,51-70,2021-08-07
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31,Alex,Verma,Lucknow,F,39.0,36-50,2024-11-09
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23,Sam,Chatterjee,Hyderabad,M,59.0,51-70,2022-03-05
3,500003,101299,Clothing,178.91,2,Card,2021-03-08,Peyton,Kohli,Jaipur,F,24.0,18-25,2023-06-05
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18,Jordan,Kumar,Pune,F,24.0,18-25,2018-04-18

In [178]:
s2 = s1.groupby(['city','customer_id']).agg(
     total_spend = ('amount' , 'sum')
).reset_index()
s2

           city  customer_id  total_spend
0     Ahmedabad       100002      3822.43
1     Ahmedabad       100054      4227.57
2     Ahmedabad       100068      4378.93
3     Ahmedabad       100112      1773.18
4     Ahmedabad       100130       642.88
...         ...          ...          ...
2516       Pune       104924        85.82
2517       Pune       104952      3263.97
2518       Pune       104965       719.95
2519       Pune       104971      3171.83
2520       Pune       104993       418.97

[2521 rows x 3 columns]

In [197]:
s3 = s2.sort_values(['city','total_spend'], ascending =[ True, False]).groupby('city').head(2)
s3

           city  customer_id  total_spend
82    Ahmedabad       101723     13992.94
74    Ahmedabad       101572      8592.35
431   Bengaluru       104026     14124.59
361   Bengaluru       102541     12113.90
575     Chennai       101747     15876.53
498     Chennai       100207     15302.52
919       Delhi       103916     11572.13
753       Delhi       100355     10374.47
1141  Hyderabad       102886     10071.76
1159  Hyderabad       103305      9773.89
1418     Jaipur       103080     19897.33
1297     Jaipur       100619     14944.99
1722    Kolkata       104256     14480.42
1675    Kolkata       103351     12756.90
1854    Lucknow       101543     14134.31
1788    Lucknow       100323     10610.22
2097     Mumbai       101230     12504.93
2273     Mumbai       104958     12393.80
2332       Pune       101304     16236.50
2438       Pune       103179     12944.99

In [206]:
s3['rank_within_city.'] = ( s3.groupby('city')['total_spend'].rank (method = 'dense',ascending =  False 
                                                               )
)

In [207]:
s3

           city  customer_id  total_spend  rank_within_city.
82    Ahmedabad       101723     13992.94                1.0
74    Ahmedabad       101572      8592.35                2.0
431   Bengaluru       104026     14124.59                1.0
361   Bengaluru       102541     12113.90                2.0
575     Chennai       101747     15876.53                1.0
498     Chennai       100207     15302.52                2.0
919       Delhi       103916     11572.13                1.0
753       Delhi       100355     10374.47                2.0
1141  Hyderabad       102886     10071.76                1.0
1159  Hyderabad       103305      9773.89                2.0
1418     Jaipur       103080     19897.33                1.0
1297     Jaipur       100619     14944.99                2.0
1722    Kolkata       104256     14480.42                1.0
1675    Kolkata       103351     12756.90                2.0
1854    Lucknow       101543     14134.31                1.0
1788    Lucknow       100323     10610.22                2.0
2097     Mumbai       101230     12504.93                1.0
2273     Mumbai       104958     12393.80                2.0
2332       Pune       101304     16236.50                1.0
2438       Pune       103179     12944.99                2.0

9 - Detect likely duplicate customers (simple heuristic) and merge

Find potential duplicate customers in cust where first_name and last_name match but customer_id differs and signup_date within 30 days. Produce a list of duplicate pairs and suggest the survivor_customer_id (earliest signup).

In [2]:
customer.head()

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27

In [3]:
transaction.head()

,transaction_id,customer_id,product_category,amount,quantity,payment_method,transaction_date
0,500000,100897,Toys,670.85,1,UPI,2024-12-22
1,500001,100465,Clothing,110.88,1,Wallet,2024-05-31
2,500002,101191,Electronics,378.66,4,UPI,2021-01-23
3,500003,101299,Clothing,178.91,2,Card,2021-03-08
4,500004,101205,Clothing,557.31,3,Netbanking,2022-09-18

In [4]:
cust = customer.copy()
cust

,customer_id,first_name,last_name,city,gender,age,age_group,signup_date
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10
1,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18
2,100002,Morgan,Verma,Ahmedabad,M,38,36-50,2021-02-04
3,100003,Robin,Bose,Pune,F,48,36-50,2020-12-31
4,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27
...,...,...,...,...,...,...,...,...
4995,104995,Alex,Bose,Delhi,M,57,51-70,2023-12-23
4996,104996,Jordan,Sharma,Ahmedabad,M,29,26-35,2019-08-03
4997,104997,Taylor,Chopra,Mumbai,M,31,26-35,2021-03-16
4998,104998,Casey,Kumar,Lucknow,F,61,51-70,2019-05-05
4999,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30

In [5]:
val = pd.merge(customer,cust, left_on = ['first_name','last_name'], right_on = ['first_name','last_name'], how = 'inner')
val

,customer_id_x,first_name,last_name,city_x,gender_x,age_x,age_group_x,signup_date_x,customer_id_y,city_y,gender_y,age_y,age_group_y,signup_date_y
0,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,100000,Ahmedabad,F,48,36-50,2020-05-10
1,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,101412,Ahmedabad,F,62,51-70,2020-11-20
2,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,101606,Ahmedabad,M,34,26-35,2021-09-03
3,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,102562,Kolkata,F,38,36-50,2020-06-02
4,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,103082,Jaipur,F,46,36-50,2024-09-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66925,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,103989,Delhi,M,66,51-70,2023-07-24
66926,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104718,Bengaluru,M,65,51-70,2023-07-31
66927,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104905,Chennai,M,66,51-70,2024-04-28
66928,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104966,Chennai,O,32,26-35,2022-12-16
66929,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104999,Pune,M,27,26-35,2024-11-30

In [6]:
val = val[val['customer_id_x'] != val['customer_id_y']]

In [7]:
val

,customer_id_x,first_name,last_name,city_x,gender_x,age_x,age_group_x,signup_date_x,customer_id_y,city_y,gender_y,age_y,age_group_y,signup_date_y
1,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,101412,Ahmedabad,F,62,51-70,2020-11-20
2,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,101606,Ahmedabad,M,34,26-35,2021-09-03
3,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,102562,Kolkata,F,38,36-50,2020-06-02
4,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,103082,Jaipur,F,46,36-50,2024-09-08
5,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,103318,Lucknow,F,53,51-70,2024-12-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66924,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,103595,Jaipur,F,35,26-35,2023-05-12
66925,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,103989,Delhi,M,66,51-70,2023-07-24
66926,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104718,Bengaluru,M,65,51-70,2023-07-31
66927,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104905,Chennai,M,66,51-70,2024-04-28
66928,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104966,Chennai,O,32,26-35,2022-12-16

In [9]:
val.loc[:, 'sign_up_diff_days'] = (
    val['signup_date_x'] - val['signup_date_y']
).abs().dt.days

In [10]:
val

,customer_id_x,first_name,last_name,city_x,gender_x,age_x,age_group_x,signup_date_x,customer_id_y,city_y,gender_y,age_y,age_group_y,signup_date_y,sign_up_diff_days
1,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,101412,Ahmedabad,F,62,51-70,2020-11-20,194
2,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,101606,Ahmedabad,M,34,26-35,2021-09-03,481
3,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,102562,Kolkata,F,38,36-50,2020-06-02,23
4,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,103082,Jaipur,F,46,36-50,2024-09-08,1582
5,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,103318,Lucknow,F,53,51-70,2024-12-10,1675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66924,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,103595,Jaipur,F,35,26-35,2023-05-12,568
66925,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,103989,Delhi,M,66,51-70,2023-07-24,495
66926,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104718,Bengaluru,M,65,51-70,2023-07-31,488
66927,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104905,Chennai,M,66,51-70,2024-04-28,216
66928,104999,Drew,Ahuja,Pune,M,27,26-35,2024-11-30,104966,Chennai,O,32,26-35,2022-12-16,715

In [11]:
duplicates = val[val['sign_up_diff_days'] <= 30]

In [12]:
duplicates

,customer_id_x,first_name,last_name,city_x,gender_x,age_x,age_group_x,signup_date_x,customer_id_y,city_y,gender_y,age_y,age_group_y,signup_date_y,sign_up_diff_days
3,100000,Blake,Verma,Ahmedabad,F,48,36-50,2020-05-10,102562,Kolkata,F,38,36-50,2020-06-02,23
11,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18,100909,Lucknow,F,20,18-25,2021-08-11,24
14,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18,101765,Bengaluru,F,20,18-25,2021-08-10,23
17,100001,Rowan,Saxena,Delhi,M,52,51-70,2021-07-18,103143,Bengaluru,F,52,51-70,2021-08-02,15
52,100004,Avery,Saxena,Bengaluru,F,36,36-50,2022-06-27,101199,Pune,M,25,18-25,2022-06-28,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66667,104982,Riley,Sharma,Hyderabad,F,18,18-25,2020-10-29,101752,Ahmedabad,F,18,18-25,2020-11-01,3
66731,104986,Taylor,Das,Hyderabad,F,27,26-35,2020-07-04,104322,Ahmedabad,F,29,26-35,2020-08-02,29
66844,104993,Skyler,Ahuja,Pune,F,66,51-70,2019-09-10,102696,Pune,F,56,51-70,2019-10-02,22
66859,104995,Alex,Bose,Delhi,M,57,51-70,2023-12-23,100433,Pune,F,54,51-70,2024-01-17,25
66901,104998,Casey,Kumar,Lucknow,F,61,51-70,2019-05-05,101451,Delhi,O,49,36-50,2019-04-29,6

In [14]:
duplicates[[
    'customer_id_x','customer_id_y',
    'first_name','last_name',
    'signup_date_x','signup_date_y',
    'sign_up_diff_days'
]]

,customer_id_x,customer_id_y,first_name,last_name,signup_date_x,signup_date_y,sign_up_diff_days
3,100000,102562,Blake,Verma,2020-05-10,2020-06-02,23
11,100001,100909,Rowan,Saxena,2021-07-18,2021-08-11,24
14,100001,101765,Rowan,Saxena,2021-07-18,2021-08-10,23
17,100001,103143,Rowan,Saxena,2021-07-18,2021-08-02,15
52,100004,101199,Avery,Saxena,2022-06-27,2022-06-28,1
...,...,...,...,...,...,...,...
66667,104982,101752,Riley,Sharma,2020-10-29,2020-11-01,3
66731,104986,104322,Taylor,Das,2020-07-04,2020-08-02,29
66844,104993,102696,Skyler,Ahuja,2019-09-10,2019-10-02,22
66859,104995,100433,Alex,Bose,2023-12-23,2024-01-17,25
66901,104998,101451,Casey,Kumar,2019-05-05,2019-04-29,6